server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
