server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
